/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    Bar: typeof import('./src/components/charts/Bar.vue')['default']
    FreightSpaceDetail: typeof import('./src/components/storehouse/FreightSpaceDetail.vue')['default']
    Gauge: typeof import('./src/components/charts/Gauge.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Iconfont: typeof import('./src/components/common/Iconfont.vue')['default']
    ImportToolManifest: typeof import('./src/components/storehouse/ImportToolManifest.vue')['default']
    InspectionDone: typeof import('./src/components/storehouse/InspectionDone.vue')['default']
    LeakReceiveTools: typeof import('./src/components/storehouse/LeakReceiveTools.vue')['default']
    Line: typeof import('./src/components/charts/Line.vue')['default']
    Pie: typeof import('./src/components/charts/Pie.vue')['default']
    RepositoryDetail: typeof import('./src/components/storehouse/RepositoryDetail.vue')['default']
    RepositoryPositionDetail: typeof import('./src/components/storehouse/RepositoryPositionDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagReadInDetail: typeof import('./src/components/storehouse/TagReadInDetail.vue')['default']
    ToolsReceiveDetail: typeof import('./src/components/storehouse/ToolsReceiveDetail.vue')['default']
    ToolsRecord: typeof import('./src/components/storehouse/ToolsRecord.vue')['default']
    UpdatePassword: typeof import('./src/components/userCenter/UpdatePassword.vue')['default']
    YmTable: typeof import('./src/components/common/YmTable.vue')['default']
  }
}
